### ISSUE TITLE
Login to twitch fails

### ISSUE THREAD

**Issue by SophieFitz** [schneidermanuel/TwitchLeecher-Dx#1]
When I go to authenticate Twitch Leecher with my Twitch account, it takes me to the login page. But when I input my information and hit enter, it tells me the browser is unsupported and so I cannot login. Can this be fixed?

If there's more info you need, let know.
Sophie

**Comment by schneidermanuel** [comment]
Thanks for reporting!

What version of Twitch Leecher DX are you using? This Bug was fixed in version 3.0.1, if you're using an older version, please update to a newer version. If you are using 3.0.1 or newer, please tell me what brower you are using or try another browser. 

Hope this helps!
