### ISSUE TITLE
Error after 3.4.0 install

### ISSUE THREAD

**Issue by missiah** [schneidermanuel/TwitchLeecher-Dx#13]
I fully removed 3.3.2!
After fresh Install of twitchleecher-dx-3.4.0-setup.exe i can't start TwitchLeecher-Dx.

I always get a [Error](https://i.imgur.com/uqb2Nn8.png)

It suggest me to download MS NetCore App after i [installed](https://i.imgur.com/uzfygED.png) that and reboted the same error occurs.

I rolled back to 3.3.2 and it's working flawless.

**Comment by schneidermanuel** [comment]
Please also install the ".NET Desktop Runtime" and ".NET Runtime" beside the ".NET Desktop Runtime"

**Comment by missiah** [comment]
Can you maybe give my direct links to the needed stuff i have to install or include them in a upcoming version? 🙏

**Comment by schneidermanuel** [comment]
Sorry, my bad! I ment to say, you need the .NET Desktop Runtime and the .NET Runtime beside the ASP.NET Runtime you installed.
ASP.NET: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.27-windows-x64-installer
.NET Desktop: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.27-windows-x64-installer
.NET: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.27-windows-x64-installer

Let me now if it helped

**Comment by missiah** [comment]
Ok that helped me a lot Thanks!
It is working now.
Appreciate your hard work.
