### ISSUE TITLE
Generic icon instead of program icon

### ISSUE THREAD

**Issue by FlamingPhoenix40** [schneidermanuel/TwitchLeecher-Dx#16]
**Description**
Ever since the version with the redesigned UI, the program no longer has the Twitch Leecher DX logo. Instead it shows a generic program icon. This is happening even on the newest version 3.5

**Steps to reproduce**
Install and run the latest version of the program.

**Information**
- Operating System: Windows 11

**Additional information that might be useful**
Thought maybe it was something about my pc, so I installed the program on a clean Windows 11 VM I recently created for something else I needed, but it behaves the same there.

![Screenshot_46](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/144808356/68263ee0-eb14-4244-b2a1-305dd833b6b3)
In the screenshot above, the last program in the row is Twitch Leecher DX.

**Comment by schneidermanuel** [comment]
I see, I need to do more testing under Windows - cause under Linux, the Icon show's up just fine. 
Thanks for reporting! I will release a fix in a few days

**Comment by FlamingPhoenix40** [comment]
When creating a different bug report today, I realized that I made this bug report in the past. However, I noticed that on the current version 3.7.1, I still have the issue of the program having a generic icon in my taskbar and in the title bar of the window.

![Screenshot_87_2024-12-08T12-46-57](https://github.com/user-attachments/assets/fc796b57-25a1-4681-877e-41e021f78b49)

**Comment by schneidermanuel** [comment]
Please try uninstalling the program and do a fresh install of the newest version, without updating an old version.

**Comment by FlamingPhoenix40** [comment]
Alright, will do that when the next fix for the other issue I reported comes out! I'll report back then!
