### ISSUE TITLE
Theme Issue? Droplist broken

### ISSUE THREAD

**Issue by mistergom** [schneidermanuel/TwitchLeecher-Dx#18]
I can add channels, but the button that allowed me to open the droplist is no longer there, on the Search Page and in the Settings... It was ok with the version 3.3.2.
And the theme seems "broken" (tabs, layout) in the recent version from 3.4.0...

Thanks for your help and keep up the GREAT work!

W11 64bits 23H2

![Screenshot_004629](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/46899060/3dafbcec-a834-4b1b-9afe-949e5d4d12ec)

![Screenshot_004630](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/46899060/0545612e-fad6-41d9-840c-d5348e9760ab)

**Comment by mistergom** [comment]
Ah! I already did a clean install and also tried to import the settings from the previous working version, without any good result...

**Comment by mistergom** [comment]
Screenshots from 3.3.2

![Screenshot_004631](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/46899060/b71ca36b-c064-4711-b938-235e82ed166c)
![Screenshot_004632](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/46899060/fdf257f0-ae3e-4c2d-a6e5-5a42d76e7336)

**Comment by mistergom** [comment]
Oh, I've just noticed that if I type the name of one of my favorite channels, the dropdown opens, but oddly...
![Screenshot_004633](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/46899060/a921ce1f-2a27-4067-9059-fb7926837661)

**Comment by schneidermanuel** [comment]
For a bit of Context, the "old UI" before 3.4, was built using WPF wich is outdated. 
In 3.4, I rewrote the UI completly, with AvaloniaUI. So when completly rewriting something, bugs are expected... 
Avalonia does not provide any editable dropdown control, so I am instead using a normal textbox with autocompletion for you favorite channels. 
I know this is not perfect, but It works until I have a better fix for this or Avalonia provides an editable dropdown.
As for the tabs, this should be fixed in 3.5.2.

**Comment by mistergom** [comment]
Thanks for the info, interesting!

Regarding the tabs, same issue with 3.5.2

![Screenshot_004634](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/46899060/7dc93b8c-d8e2-4ac5-bb69-1d1f218c916a)

**Comment by schneidermanuel** [comment]
It looks different, but they work! With 3.4.2, they did not work as expected

**Comment by mistergom** [comment]
Thanks a lot for the updates! Great job and good luck for the future! ;)

**Comment by schneidermanuel** [comment]
@mistergom this is an issue in the "light" theme. You can get the dark theme by changing your window's settings, it looks better in the dark mode. From the next version on, TwitchlLecher-DX will use the dark version, no matter what you use in windows.

**Comment by mistergom** [comment]
OK I see, thank you!
