### ISSUE TITLE
Not literal directory names

### ISSUE THREAD

**Issue by Zi0MIX** [schneidermanuel/TwitchLeecher-Dx#19]
**Description**

Path

```
E:\temp - fr\town
```

is interpreted like so

```
E:/temp%20-%20fr/town
```

![image](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/80110206/1218b7d3-b528-46c9-b4d7-a6d649c5c0fd)

Starting the download does in fact create a new directory with the modified name

![image](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/80110206/26f442a5-f558-4ac6-ad07-eeec67946c9c)

**Steps to reproduce**
Create a directory with spaces in the name, select it for the download, then start it

**Information**
Win10 64bit

**Comment by schneidermanuel** [comment]
Fixed with #21
