### ISSUE TITLE
VOD thumbnail click does not open the video in web browser

### ISSUE THREAD

**Issue by Zi0MIX** [schneidermanuel/TwitchLeecher-Dx#22]
**Description**
When clicking on a thumbnail of a VOD in search tab, the video does not open in the web browser

**Steps to reproduce**
Search any content and press on the thumbnail, cursor changes it's shape but the hypelink does not open

**Information**
- Win10 PRO
Not sure what kind of info would be helpful here, so feel free to ask for details that are needed

**Comment by schneidermanuel** [comment]
Closed with #23
