### ISSUE TITLE
Twitch Leecher-DX error when downloading

### ISSUE THREAD

**Issue by franklinalvarezn** [schneidermanuel/TwitchLeecher-Dx#24]
**Description**
**

> When trying to start any download it shows me this error

**

**Steps to reproduce**

> **I open the TwitchLecher-DX program, copy the link or use any search method for the program to download and after several minutes it shows me the error message.**

**Information**
**- Twitch VOD URL:** 

> https://www.twitch.tv/videos/2126641239

**- Twitch Leecher-DX log file**

> Download task has been started!
> 
> TWITCH LEECHER INFO
> --------------------------------------------------------------------------------------------
> Version: 3.5.6
> 
> VOD INFO
> --------------------------------------------------------------------------------------------
> VOD ID: 2126641239
> Selected Quality: 1080p60 (1920x1080)
> Download Url: https://www.twitch.tv/videos/2126641239
> Crop Start: No
> Crop End: No
> 
> OUTPUT INFO
> --------------------------------------------------------------------------------------------
> Disable Conversion: Yes
> Output File: C:/Users/Frank/Videos\22-04 alexelcapo.ts
> FFMPEG Path: C:\Program Files (x86)\TwitchLeecher-Dx\ffmpeg.exe
> Temporary Download Folder: C:\Users\Frank\AppData\Local\Temp\3da849342590493ebffb31f5770fc153
> 
> Retrieving VOD access information... done!
> 
> ACCESS INFO
> --------------------------------------------------------------------------------------------
> Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1713911084%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A2126641239%7D
> Signature: 7bb355610008091baa5805924ec9bdd9eafa6f73
> Sub-Only: No
> Privileged: No
> 
> Creating temporary download directory 'C:\Users\Frank\AppData\Local\Temp\3da849342590493ebffb31f5770fc153'... done!
> 
> Retrieving playlist information for all VOD qualities... done!
> 
> PLAYLIST INFO
> --------------------------------------------------------------------------------------------
> Playlist for quality '1080p60' is 'https://d1m7jfoe9zdc1j.cloudfront.net/4fb76b00711cc7c457d3_alexelcapo_50940460845_1713796152/chunked/index-dvr.m3u8'
> Playlist for quality '720p60' is 'https://d1m7jfoe9zdc1j.cloudfront.net/4fb76b00711cc7c457d3_alexelcapo_50940460845_1713796152/720p60/index-dvr.m3u8'
> Playlist for quality '480p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/4fb76b00711cc7c457d3_alexelcapo_50940460845_1713796152/480p30/index-dvr.m3u8'
> Playlist for quality 'Audio Only' is 'https://d1m7jfoe9zdc1j.cloudfront.net/4fb76b00711cc7c457d3_alexelcapo_50940460845_1713796152/audio_only/index-dvr.m3u8'
> Playlist for quality '360p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/4fb76b00711cc7c457d3_alexelcapo_50940460845_1713796152/360p30/index-dvr.m3u8'
> Playlist for quality '160p' is 'https://d1m7jfoe9zdc1j.cloudfront.net/4fb76b00711cc7c457d3_alexelcapo_50940460845_1713796152/160p30/index-dvr.m3u8'
> 
> Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d1m7jfoe9zdc1j.cloudfront.net/4fb76b00711cc7c457d3_alexelcapo_50940460845_1713796152/chunked/index-dvr.m3u8'
> 
> Retrieving playlist... done!
> Parsing playlist... done!
> Number of video chunks: 1742
> 
> Starting parallel video chunk download
> Number of video chunks to download: 1742
> Maximum connection count: 10
> 
> Parallel video chunk download is running...
> 
> Starting temporary download folder cleanup!
> Deleting directory 'C:\Users\Frank\AppData\Local\Temp\3da849342590493ebffb31f5770fc153'... done!
> 
> Download task ended with an error!
> 
> System.AggregateException: One or more errors occurred. (One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.) (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.))
>  ---> System.AggregateException: One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.) (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.)
>  ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
>  ---> System.TimeoutException: The operation was canceled.
>  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
>  ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
>  ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
>    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
>    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
>    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
>    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
>    at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 528
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__1(Int32 i, ParallelLoopState state)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
>    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
>    at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 514
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2() in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 227
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
>  ---> (Inner Exception #1) System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
>  ---> System.TimeoutException: The operation was canceled.
>  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
>  ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
>  ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
>    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
>    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
>    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
>    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
>    at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 528
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__1(Int32 i, ParallelLoopState state)
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
>    at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
> 
>    --- End of inner exception stack trace ---

**- Operating System**

> Windows 11 Pro 23H2 OS BUILD 22631.3447

**Additional information that might be useful**

**

> I have tried several vods, however I always have the same error.

**

**Comment by positron7120** [comment]
@franklinalvarezn could you check whether version 3.6.0 has fixed this error for you? As, it is fixed for me.

**Comment by schneidermanuel** [comment]
Is this error still present in the current version 3.6?

**Comment by positron7120** [comment]
It seems to be resolved now.

**Comment by Vaborgabe** [comment]
Im getting this issue in 3.7.4, seems to be occurring when Im not tabbed into the app
```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 3.7.4

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 2479792581
Selected Quality: 1080p60 (1920x1080)
Download Url: https://www.twitch.tv/videos/2479792581
Crop Start: No
Crop End: Yes (03:20:30)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Disable Conversion: No
Output File: E:\PM\Project Management\Work\Nandre\25-7-5 Jerma Invitational\VODS\PT 1\PT 1 QT POV.mp4
FFMPEG Path: C:\Program Files (x86)\TwitchLeecher-Dx\ffmpeg.exe
Temporary Download Folder: E:\Editing\!Video Assets\TEMP\cc66770904544cb0b4afaf9c9e888c6d

Retrieving VOD access information... done!

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1751851998%2C%22https_required%22%3Atrue%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A3%2C%22vod_id%22%3A2479792581%2C%22maximum_resolution%22%3A%22FULL_HD%22%2C%22maximum_video_bitrate_kbps%22%3A12500%2C%22maximum_resolution_reasons%22%3A%7B%22QUAD_HD%22%3A%5B%22AUTHZ_NOT_LOGGED_IN%22%5D%2C%22ULTRA_HD%22%3A%5B%22AUTHZ_NOT_LOGGED_IN%22%5D%7D%2C%22maximum_video_bitrate_kbps_reasons%22%3A%5B%22AUTHZ_DISALLOWED_BITRATE%22%5D%7D
Signature: 356285871fe6c244f2e46f7cb57d17b4c5aef853
Sub-Only: No
Privileged: No

Creating temporary download directory 'E:\Editing\!Video Assets\TEMP\cc66770904544cb0b4afaf9c9e888c6d'... done!

Retrieving playlist information for all VOD qualities... done!

PLAYLIST INFO
--------------------------------------------------------------------------------------------
Playlist for quality '1080p60' is 'https://d2nvs31859zcd8.cloudfront.net/590947a72d3b1eb6cead_qtcinderella_322262469884_1749321902/1080p60/index-dvr.m3u8'
Playlist for quality '720p60' is 'https://d2nvs31859zcd8.cloudfront.net/590947a72d3b1eb6cead_qtcinderella_322262469884_1749321902/720p60/index-dvr.m3u8'
Playlist for quality '480p' is 'https://d2nvs31859zcd8.cloudfront.net/590947a72d3b1eb6cead_qtcinderella_322262469884_1749321902/480p30/index-dvr.m3u8'
Playlist for quality '360p' is 'https://d2nvs31859zcd8.cloudfront.net/590947a72d3b1eb6cead_qtcinderella_322262469884_1749321902/360p30/index-dvr.m3u8'
Playlist for quality 'Audio Only' is 'https://d2nvs31859zcd8.cloudfront.net/590947a72d3b1eb6cead_qtcinderella_322262469884_1749321902/audio_only/index-dvr.m3u8'
Playlist for quality '160p' is 'https://d2nvs31859zcd8.cloudfront.net/590947a72d3b1eb6cead_qtcinderella_322262469884_1749321902/160p30/index-dvr.m3u8'

Playlist url for selected quality '1080p60 (1920x1080)' is 'https://d2nvs31859zcd8.cloudfront.net/590947a72d3b1eb6cead_qtcinderella_322262469884_1749321902/1080p60/index-dvr.m3u8'

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 2577

Starting parallel video chunk download
Number of video chunks to download: 1203
Maximum connection count: 20

Parallel video chunk download is running...

Starting temporary download folder cleanup!
Deleting directory 'E:\Editing\!Video Assets\TEMP\cc66770904544cb0b4afaf9c9e888c6d'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. (One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.))
 ---> System.AggregateException: One or more errors occurred. (The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.)
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass27_0.<DownloadParts>b__0(TwitchPlaylistPart part, ParallelLoopState loopState) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 528
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`2 body)
   at TwitchLeecher.Services.Services.DownloadService.DownloadParts(Action`1 log, Action`1 setStatus, Action`1 setProgress, TwitchPlaylist vodPlaylist, CancellationToken cancellationToken) in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 514
   at TwitchLeecher.Services.Services.DownloadService.<>c__DisplayClass19_0.<StartQueuedDownloadIfExists>b__2() in E:\Coding\twitchleecher-dx\TwitchLeecher\TwitchLeecher.Services\Services\DownloadService.cs:line 227
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```
