### ISSUE TITLE
All the results of the channels simultaneously?

### ISSUE THREAD

**Issue by mistergom** [schneidermanuel/TwitchLeecher-Dx#27]
Hello! Thanks a lot for the recent version; it's perfect ;)

I'm following several channels and I was wondering if it would be possible to have an option to aggregate the results from all the channels together on the same results page? Like if you could conduct a global search and it would display like on YouTube, with your own subscriptions all "mixed together"?

All the best!

**Comment by schneidermanuel** [comment]
its planed, but I didn't start to work on it.
For now, the Idea idea is that you are able to perform a search through all your favorite channels.

**Comment by mistergom** [comment]
Sounds great! Good luck!
