### ISSUE TITLE
URLs invalid

### ISSUE THREAD

**Issue by Superspaz** [schneidermanuel/TwitchLeecher-Dx#28]
When trying to download any vod that's around 24hrs old or newer the search box is highlighted in red and the message "One or more URLs are invalid!" is displayed. The same thing happens with ID search.

I was still on 3.5.6 when this first happened and found out a newer version has been released so I thought installing 3.5.7 would most likely fix it but the error is still occurring exactly the same way.
**Steps to reproduce**
Attempt to search a vod by URL or ID that's been out for less than a day.

**Comment by saitek93** [comment]
The code has to be changed to use int64, because int32 can't work with VODs thats ID is past 2147483647.

Hoping for an update soon.

**Comment by schneidermanuel** [comment]
Thanks for the Input, will have a look at this this week

**Comment by schneidermanuel** [comment]
> The code has to be changed to use int64, because int32 can't work with VODs thats ID is past 2147483647.
> 
> Hoping for an update soon.

This helped me a lot. Fixed with #32
