### ISSUE TITLE
Can't activate sub-only support

### ISSUE THREAD

**Issue by Flwk** [schneidermanuel/TwitchLeecher-Dx#3]
Hello

I'm using Twitch Leecher DX Version 3.1.1 on W10 64Bit and I have a problem to activate sub-only download support.

When I click on the button, nothing happen.  I'm connected on my Twitch Account. 

What can I do ?

Thanks in advance

**Comment by schneidermanuel** [comment]
This is a known problem, I am trying to get it fixed within the next days
