### ISSUE TITLE
Banned channels break Favorites search

### ISSUE THREAD

**Issue by Brumm89** [schneidermanuel/TwitchLeecher-Dx#33]
If someone in your favorite channels list is banned, the whole search favorites tab won't load any results. It just loads some time and instead of skipping the channel, just goes back to the search tab. Would be cool if it just skips temp. banned channels in the future and just load the remaining ones (+ maybe giving out a little info message at the end to know which ones are affected).

**Comment by schneidermanuel** [comment]
Thanks for reporting, I will have a look at this

**Comment by schneidermanuel** [comment]
Closed with v3.6.1, thanks for reporting!
