### ISSUE TITLE
Muted parts

### ISSUE THREAD

**Issue by satrincha** [schneidermanuel/TwitchLeecher-Dx#41]
i, Thank you to continue the project of Twitch Leecher, i am happy to found you :) 

There is nothing to do against the muted parts ?
When twitch mute a part, it's gone ?

edit : sorry it's not a bug, i am not used to post on github, i can't find how to change labels, sorry.

**Comment by schneidermanuel** [comment]
Sadly, there is nothing to do about it as twitch completly deletes the parts on the server. 
In general, it takes twitch up to an hour after the stream has ended to delete the muted parts, so if you start the download right after the end of the stream, it is most likly possible to download the whole thing with audio, at least this works like 90% of the time for me. Once the audio is gone, there is nothing to do about it, sorry

**Comment by satrincha** [comment]
Ok, thank for the tip. i miss the recording last night, but i could retreave 2h25 of 3h ! Thank to you :)
