### ISSUE TITLE
Sudden Crash

### ISSUE THREAD

**Issue by Brumm89** [schneidermanuel/TwitchLeecher-Dx#44]
Suddenly crashes while searching the fav channels tab. After i've gone through all my channels only "Shylily" seem to trigger the crash. She's not even banned or was banned in the past days so i really have no idea why just her channel triggers it. Also i get no crash log sadly (no new log in AppData\Roaming\Twitch Leecher DX\logs).

**Comment by schneidermanuel** [comment]
Thanks! 
It also happens when searching the channel directly.
I will investigate this asap

**Comment by schneidermanuel** [comment]
This turned out to be a bug in the UI Framework "Avalonia", which Twitch Leecher DX uses and it seems to be unable to render certain characters which appear in some video titles in Shylily's channel. Upgrading the version of Avalonia to latest resolved this issue
