### ISSUE TITLE
Windows defender warning

### ISSUE THREAD

**Issue by heymeghan** [schneidermanuel/TwitchLeecher-Dx#46]
**Description**
Windows defender warns that the program could harm my PC. 

**Steps to reproduce**
opening the application for the first time so i'm unsure how to reproduce it. i suppose with a clean install? 

**Information**
![Screenshot 2024-09-06 135816](https://github.com/user-attachments/assets/f6d79b8f-dea4-4bf8-be93-c387b4b91267)

**Comment by schneidermanuel** [comment]
I currently have no intentions of fixing this. 
You can still install and use this program as normal by pressing "More info" and "run anyways".
