### ISSUE TITLE
sub only mode: couldn't find a valid token

### ISSUE THREAD

**Issue by deaFPS** [schneidermanuel/TwitchLeecher-Dx#5]
Hey im using the latest leecher version of this fork and i cant get sub only mode to work..

everytime i try to enable it i says that it couldn't find a valid token, is there a way to set the token manually? if not a feature like that would be handy.. to have a text box somewhere where you can enter the token by hand

**Comment by schneidermanuel** [comment]
What operating system are you using?

Make sure you are logged in to twitch in a Webbrowser like firefox, google Chrome, etc. 
A feature to input a token manually is planed and will be added in a future release.

**Comment by schneidermanuel** [comment]
Closed with release v3.3.0
