### ISSUE TITLE
Delete or upgrade impossible with old TwitchLeecher

### ISSUE THREAD

**Issue by Mohmotte** [schneidermanuel/TwitchLeecher-Dx#6]
It's impossible to delete or upgrade with old TwitchLeecher

![Nouveau Image bitmap](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/71752639/be04f807-6ada-4a9c-b4c6-321962201f5a)

**Comment by schneidermanuel** [comment]
Thanks for reporting!

Can you try using the latest Version 3.3.0?

**Comment by Mohmotte** [comment]
I try all older versions

**Comment by schneidermanuel** [comment]
Ok, I will try to reproduce this behaviour, for now, please uninstall TwitchLeecher manually, then install the latest version from here

**Comment by Mohmotte** [comment]
Uninstall TwitchLeecher manually doesn't work...

**Comment by schneidermanuel** [comment]
I will adress this issue with the next release.

**Comment by schneidermanuel** [comment]
This is on hold for now. 
I am working on upgrading this to .net 6.0 and with this change, I will compleatly rewrite the installer and use another library than Wix. 
I will implement a fix in the new version, but this requires time.

For now, It is required to compleatly remove Twitch Leecher before installing this fork. 
If uninstalling Twitch Leecher does not work, try upgrading to the newest version of Twitch Leecher first.

**Comment by Mohmotte** [comment]
![Capture d’écran (272)](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/71752639/04a81871-3c59-4d74-a875-544b085af3e6)
Thanks

**Comment by schneidermanuel** [comment]
Thanks for the information, if some day, the config files differ from dx to the old version, I will implement a method to import your settings from an existing Twitch Leecher configuration!

**Comment by schneidermanuel** [comment]
I mark this as resolved for now.
If anyone encouters a simmilar problem, open up a new issue.
