### ISSUE TITLE
Apologies, how to install?

### ISSUE THREAD

**Issue by Jaybonaut** [schneidermanuel/TwitchLeecher-Dx#9]
All I see are folders and I am unfamiliar with GitHub.  How does one go about installing this brilliant piece of software?

**Comment by schneidermanuel** [comment]
Hey, If you aren't familiar with github, the folders you see on the main page contain the whole source code of the project. To install it, navigate to the "releases" section in the right side of the page and select the newest release (Version 3.3.2 as of December 2023). 
In the "Assets" section of the release, you find a .exe file which you can download and install the software. 
Currentiy, only Windows is supportet, a Linux release is beeing planed. 
Let me now if this helps out

**Comment by Jaybonaut** [comment]
I appreciate it, thank you.
